language: go

services:
  - docker
go:
  - 1.14

env:
  global:
    - GO111MODULE=on
    - COMMIT=${TRAVIS_COMMIT::8}
    - REPO=mskj/kubeadm-ignition-bootstrap-controller

before_script:
  - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"

script:
  - fossa init
  - fossa analyze
  - export TAG=`if [ -e "$TRAVIS_TAG" ]; then echo "$TRAVIS_TAG"; else echo $COMMIT ; fi`
  - make docker-build IMG=${REPO}:${TAG}
  - make release IMG=${REPO}:${TAG}

after_success:
  - fossa test
deploy:
  - provider: script
    script: bash docker_push.sh
    on:
      branch: etcd
  - provider: releases
    api_key: "${GITHUB_OAUTH_TOKEN}"
    file: "config/bootstrap-components.yaml"
    skip_cleanup: true
    on:
      tags: true