language: go

services:
  - docker
go:
  - 1.14

env:
  global:
    - GO111MODULE=on
    - COMMIT=${TRAVIS_COMMIT::8}
    - REPO=mskj/kubeadm-bootstrap-controller-ignition

before_script:
	- "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"

script:
  - fossa init
  - fossa analyze
  - docker build -t ${REPO}:${COMMIT} -f Dockerfile .

after_success:
    - fossa test
deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master